# Basic
title: ScorpioHuang
subtitle: 骏马面前无沟壑,怂人脚下全是坎。
welcome_message: 欢迎来到我的个人网站！
description: 嘿！我是ScorpioHuang，是一名小小的web前端开发，目前边提升边工作，致力于web前端的研究和应用,努力成为一名优秀的前端开发工程师。
creator: <a href="http:www.hcuij.com">@hcj</a>

url: "http://www.hcuij.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 动态效果网站, description: My Projects, url: 'www.baidu.com'}
    - {title: 动态效果网站, description: My Projects, url: 'www.baidu.com'}
    - {title: 动态效果网站, description: My Projects, url: 'www.baidu.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
